### PR TITLE
Stringify `managedZoneId`

### LINKED ISSUE #1036: managedZoneId does not match the actual dns managed_zone id.
### What happened?

Managing a private DNS zone in GCP with Pulumi, giving access to the zone from other networks in the organization.  I can create a new zone, and populate it with networks.  But then I can no longer add/remove networks, or delete the zone using Pulumi.

I can still manage the zone using the gcloud cli.

Pulumi will throw this error:
```
    error: 1 error occurred:
    	* updating urn:pulumi:brinqa-prod::brinqa-net-private::gcp:dns/managedZone:ManagedZone::brinqa-net-private: 1 error occurred:
    	* Error updating ManagedZone "projects/brinqa-prod/managedZones/brinqa-net-private": googleapi: Error 400: The field 'entity.managedZone.id' cannot be modified., immutableField
```

### Expected Behavior

That Pulumi can add/remove networks after initial creation.

### Steps to reproduce

Start with something like:
```
import pulumi
import pulumi_gcp as gcp

private_zone = gcp.dns.ManagedZone("private",
    cloud_logging_config=gcp.dns.ManagedZoneCloudLoggingConfigArgs(
        enable_logging=False,
    ),
    description="private",
    dns_name="example.net.",
    name="private",
    private_visibility_config=gcp.dns.ManagedZonePrivateVisibilityConfigArgs(
        networks=[
            gcp.dns.ManagedZonePrivateVisibilityConfigNetworkArgs(
                network_url="https://www.googleapis.com/compute/v1/projects/project-a/global/networks/project-a-vpc",
            ),
            gcp.dns.ManagedZonePrivateVisibilityConfigNetworkArgs(
                network_url="https://www.googleapis.com/compute/v1/projects/project-b/global/networks/project-b-vpc",
            ),
        ],
    ),
    project="dns-project",
    visibility="private",
    opts=pulumi.ResourceOptions(protect=True))
```

Then either remove one of the network_urls, or add a third one.  You will receive the error above.

### Output of `pulumi about`

(slightly edited to mask urn identifiers)
```
CLI          
Version      3.58.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.51.0
python  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.8.10
'

Current Stack: brinqa-prod

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:xx-prod::xx-net-private::pulumi:pulumi:Stack::xx-net-private-xxx-prod
pulumi:providers:gcp             urn:pulumi:xx-prod::xxx-net-private::pulumi:providers:gcp::default_6_51_0
gcp:dns/managedZone:ManagedZone  urn:pulumi:xx-prod::xx-net-private::gcp:dns/managedZone:ManagedZone::xx-net-private


Found no pending operations associated with xx-prod

Backend        
Name           cm
URL            gs://xxpulumi-state
User           jnelson
Organizations  

Dependencies:
NAME           VERSION
pip            23.0.1
pkg_resources  0.0.0
pulumi-gcp     6.51.0
setuptools     67.6.0
wheel          0.40.0

Pulumi locates its logs in /tmp by default
```

### Additional context

I've traced this down to how ints get cast into scientific notation and back.

From a `pulumi up -v=9 --logtostderr` run:

```
I0321 22:26:23.855003 2409260 log.go:75] Marshaling property for RPC[Provider[gcp, 0xc00042fd10].Diff(urn:pulumi:brinqa-prod::brinqa-net-private::gcp:dns/managedZone:ManagedZone::brinqa-net-private,projects/brinqa-prod/managedZones/brinqa-net-private).olds]: managedZoneId={2.9610687372243656e+18}
```

Note: `managedZoneId={2.9610687372243656e+18}`
Then when it tries to perform the update:

```
I0321 22:26:41.900974 2409260 log.go:75] Updating ManagedZone "projects/xx-prod/managedZones/xx-net-private": map[string]interface {}{"cloudLoggingConfig":map[string]interface {}{}, "creationTime":"2023-03-21T17:05:13.497Z", "description":"xx-net-private", "dnsName":"xx.net.", "id":2961068737224365600, "name":"xx-net-private", "nameServers":[]interface {}{"ns-gcp-private.googledomains.com."}, "privateVisibilityConfig":map[string]interface {}{"networks":[]interface {}{map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-cicd/global/networks/cicd-vpc"}, map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-sales/global/networks/sales-vpc"}, map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-cs/global/networks/cs-vpc"}, map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-core/global/networks/core-vpc"}, map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-trial-pcc/global/networks/pcc-vpc"}, map[string]interface {}{"networkUrl":"https://www.googleapis.com/compute/v1/projects/xx-qa/global/networks/qa-vpc"}}}, "visibility":"private"}
```

Note: `"id":2961068737224365600` which is the expanded form of `2.9610687372243656e+18`

My actual zone id is:
```
$ gcloud dns managed-zones describe xx-net-private --project=xx-prod --format="json(id)"
{
  "id": "2961068737224365485"
}
```
(also google's API return this as a string)

Let me know if you need any additional info

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #1036

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
looks good, we should make sure to call out the breaking change in the release notes

File: provider/resources.go [hunk 1]
```diff
@@ -4018,6 +4020,23 @@ func Provider() tfbridge.ProviderInfo {
 
 	fixLabelNames(&prov)
 
+	// managed_zone_id is an ID masquerading as an int64. Since it uses the full 64
+	// bits it has, we need to stringify it to keep more data then a number (float64)
+	// will allow.
+	//
+	// https://github.com/pulumi/pulumi-gcp/issues/1036
+	tfbridge.MustTraverseProperties(&prov, "managed_zone",
```
Comment (t0yv0) [inline provider/resources.go:4028]: This may slow down startup time. Just FYI. In the case of AWS there are schemas that are hidden behind SchemaFunc() to make them lazy, and traversals of this kind force them to materialize into memory which creates pressure and can cost some significant ms on startup as well as RAM usage. Perhaps not a problem for GCP.

**Review by t0yv0 — APPROVED** [review]

File: provider/resources.go (hunk 1 above)
Comment (VenelinMartinov) [reply provider/resources.go:4028]: I believe Ian added something clever in the bridge which saves the relevant resources in the bridge metadata and only acts on them during startup.

Comment (iwahbe) [reply provider/resources.go:4028]: Yep. `MustTraverseProperties` does slow startup time during `make tfgen`. It computes a list of effected properties then, and only visits properties that need overrides during normal runtime.

Comment (t0yv0) [reply provider/resources.go:4028]: Ohh so it's already optimized. Brilliant.
