### PR TITLE
Fix up note on `gcp.kms.CryptoKey` to show Pulumi resource option

### LINKED ISSUE #1879: Fix `gcp.kms.CryptoKey` documentation to suggest `resource option protect` instead of a lifecycle hook
### What happened?

A user brought it to my attention the gcp.kms.CryptoKey resource has the following note 

> Note: CryptoKeys cannot be deleted from Google Cloud Platform. Destroying a provider-managed CryptoKey will remove it from state and delete all CryptoKeyVersions, rendering the key unusable, but will not delete the resource from the project. When the provider destroys these keys, any data previously encrypted with these keys will be irrecoverable. For this reason, it is strongly recommended that you add lifecycle hooks to the resource to prevent accidental destruction.

I believe this is leftover from the bridged TF documentation and should be updated to be the resource option `protect`

### Example

Link to the resource documentation: https://www.pulumi.com/registry/packages/gcp/api-docs/kms/cryptokey/

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
Fixes #1879.

### CODE REVIEW

File: provider/doc_edits.go [hunk 1]
```diff
@@ -112,3 +114,20 @@ var rewritemembersField = tfbridge.DocsEdit{
...
+		},
+	}
+}
+
+var fixUpKmsCryptoKey = targetedSimpleReplace(
+	"kms_crypto_key.html.markdown",
+	"For this reason, it is strongly recommended that you add\nlifecycle\nhooks "+
+		"to the resource to prevent accidental destruction.",
+	"For this reason, it is strongly recommended that you use the "+
+		"[pulumi protect resource option](https://www.pulumi.com/docs/concepts/options/protect/)")
```
Comment (iwahbe) [inline provider/doc_edits.go:133]:
```suggestion
	"For this reason, it is strongly recommended that you use the "+
		"Pulumi's [protect resource option](https://www.pulumi.com/docs/concepts/options/protect/)",
)
```

**Review by iwahbe — APPROVED** [review]
